version: '3.8'

services:
  php:
    image: php:8.2-fpm
    working_dir: "/var/www/html"
    volumes:
      - ".:/var/www/html"
    ports:
      - "9001:9000"

  nginx:
    image: nginx
    volumes:
      - "./docker/new.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - php

  composer:
    image: composer
    volumes:
      - ".:/app"
    command: install







